In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(filepath_or_buffer="./oil_category_2.csv",delimiter="|")
df.head()

,data,labels
0,"The consortium, led by U.S. firm EIG Global En...",Not Relevant
1,The unplanned shutdown two weeks ago of Syncru...,Supply Negative#Uncertain Label
2,Pemex lost $7.7 billion during the first half ...,Not Relevant
3,A spokesman for New York State Comptroller Tho...,Not Relevant
4,(Reuters) — Exxon Mobil Corporation on Tuesday...,Supply Negative

In [3]:
df.dropna(inplace=True)
df['labels'] = df['labels'].str.split("#", expand=False)
labels = ['Prices Positive','Prices Negative','Supply Positive','Supply Negative','Demand Positive','Demand Negative','Future','Current','Intermediate','Not Relevant']
for i in range(0,len(labels)):
    df[labels[i]] = np.zeros((len(df),1)).astype(int)
# Kill label and turn it into the 0 and 1 columns
for category in labels:
    df[category] = df['labels'].apply(lambda cat: 1 if category in cat else 0)
df.drop(['labels'],axis=1,inplace=True)
df.head()

,data,Prices Positive,Prices Negative,Supply Positive,Supply Negative,Demand Positive,Demand Negative,Future,Current,Intermediate,Not Relevant
0,"The consortium, led by U.S. firm EIG Global En...",0,0,0,0,0,0,0,0,0,1
1,The unplanned shutdown two weeks ago of Syncru...,0,0,0,1,0,0,0,0,0,0
2,Pemex lost $7.7 billion during the first half ...,0,0,0,0,0,0,0,0,0,1
3,A spokesman for New York State Comptroller Tho...,0,0,0,0,0,0,0,0,0,1
4,(Reuters) — Exxon Mobil Corporation on Tuesday...,0,0,0,1,0,0,0,0,0,0

In [12]:
for label in labels:
    print(label + " " + str(df[label].value_counts()[1]))

Prices Positive 25
Prices Negative 32
Supply Positive 60
Supply Negative 52
Demand Positive 16
Demand Negative 22
Future 38
Current 16
Intermediate 62
Not Relevant 200